
#ifndef TINY_LOG_TINY_LOG_CONFG_H
#define TINY_LOG_TINY_LOG_CONFG_H

#define TINY_LOG_LOG_LEVEL ${TINY_LOG_LEVEL}
#define TINY_LOG_ENABLE_FLOAT ${TINY_LOG_ENABLE_FLOAT}
#define TINY_LOG_SECTION_NAME ${TINY_LOG_SECTION}
#define TL_DO_EXPAND(X) X ## 1
#define TL_EXPAND(VAL) TL_DO_EXPAND(VAL)
#if TL_EXPAND(TINY_LOG_SECTION_NAME) != 1
#define TINY_LOG_LOG_SECTION __attribute__ ((section (".${TINY_LOG_SECTION}")))
#define TINY_LOG_LOG_SECTION_RO __attribute__ ((section (".${TINY_LOG_SECTION}.ro")))
#else
#define TINY_LOG_LOG_SECTION
#define TINY_LOG_LOG_SECTION_RO
#endif



#endif //TINY_LOG_TINY_LOG_CONFG_H
